name: Deploy to Production
on:
  workflow_dispatch:
    inputs:
      release_version:
        description: 'Release version to deploy (number)'
        required: true

env:
  REGISTRY_ID: crperh81ttnqgnsobd6c
  APP_NAME: app
  VM_IP: 51.250.29.116
  SSH_USER: olechkakulic

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Setup environment
        run: |
          echo "Preparing to deploy version ${{ github.event.inputs.release_version }}"
          
      - name: Install YC CLI
        run: |
          curl -s https://storage.yandexcloud.net/yandexcloud-yc/install.sh | bash
          echo "$HOME/yandex-cloud/bin" >> $GITHUB_PATH

      - name: Authenticate in Container Registry
        env:
          YC_SA_KEY: ${{ secrets.YC_SA_KEY }}
        run: |
          echo "$YC_SA_KEY" > key.json
          yc config set service-account-key key.json
          IAM_TOKEN=$(yc iam create-token)
          
          if ! echo "$IAM_TOKEN" | docker login --username iam --password-stdin cr.yandex; then
            echo "::error::Failed to login to container registry"
            exit 1
          fi

      - name: Verify image exists
        run: |
          if ! docker manifest inspect cr.yandex/${{ env.REGISTRY_ID }}/${{ env.APP_NAME }}:${{ github.event.inputs.release_version }}_latest; then
            echo "::error::Image not found in registry"
            exit 1
          fi

      - name: Deploy to VM
        env:
          SSH_KEY: ${{ secrets.VM_SSH_KEY }}
        run: |
          echo "$SSH_KEY" > ssh_key
          chmod 600 ssh_key
          
          # Store commands in a variable to properly handle the version parameter
          DEPLOY_SCRIPT=$(cat <<EOF
            # Clean up existing container if it exists
            docker stop app || true
            docker rm app || true
            
            # Authenticate using the VM's service account
            curl -s --header "Metadata-Flavor: Google" \\
              "http://169.254.169.254/computeMetadata/v1/instance/service-accounts/default/token" | \\
              cut -f1 -d',' | \\
              cut -f2 -d':' | \\
              tr -d '"' | \\
              docker login --username iam --password-stdin cr.yandex
            
            # Pull and run the new version
            export REGISTRY_ID=$REGISTRY_ID
            docker pull cr.yandex/$REGISTRY_ID/$APP_NAME:${{ github.event.inputs.release_version }}_latest
            docker run -d -p 80:3000 --name app cr.yandex/$REGISTRY_ID/$APP_NAME:${{ github.event.inputs.release_version }}_latest
          EOF
          )
          
          # Execute the script on the remote machine
          ssh -i ssh_key -o StrictHostKeyChecking=no ${{ env.SSH_USER }}@${{ env.VM_IP }} "$DEPLOY_SCRIPT"

      - name: Add Deployment Comment to Release Issue
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Find issue by release version
          ISSUE_NUMBER=$(gh issue list --search "Release v${{ github.event.inputs.release_version }}" --json number -q '.[0].number')
          
          if [ -z "$ISSUE_NUMBER" ]; then
            echo "Issue for release v${{ github.event.inputs.release_version }} not found!"
            exit 0
          fi
          
          # Create deployment comment
          gh issue comment $ISSUE_NUMBER \
            --body "**Релиз выкачен в прод**  
                    **Версия:** ${{ github.event.inputs.release_version }}  
                    **Запустил деплой:** ${{ github.actor }}  
                    **Docker Image:** cr.yandex/${{ env.REGISTRY_ID }}/${{ env.APP_NAME }}:${{ github.event.inputs.release_version }}_latest  
                    **Дата выкатки:** $(date +'%Y-%m-%d %H:%M %Z')"
